baseURL: "/"
languageCode: "en-us"
title: "Learner Loft"
theme: "PaperMod"

staticDir: ["static"]

markup:
  goldmark:
    renderer:
      unsafe: true

ignoreFiles:
  - "static/devtools/*"

security:
  funcs:
    getenv:
      - ^HUGO_
      - ^NODE_

# Suppress HTML warnings
ignoreLogs:
  - 'warning-goldmark-raw-html'

params:
  defaultTheme: auto
  ShowBreadCrumbs: true
  ShowBreadCrumbsOnHome: false
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  
  homeInfoParams:
    Title: "Welcome to Learner Loft"
    Content: "A place to learn and grow together"

  socialIcons:
    - name: "github"
      url: "https://github.com/yourusername"

  ShowAllPagesInArchive: true
  ShowPageNums: true

  cover:
    linkFullImages: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowRssButtonInSectionTermList: true

  ShowToc: true


menu:
  main:
    - identifier: devtools
      name: Dev Tools
      url: /devtools/
      weight: -100
    - identifier: sql
      name: SQL
      url: /sql/
      weight: -90
    - identifier: html
      name: HTML
      url: /html/
      weight: -80
    - identifier: oracleapex
      name: Oracle APEX
      url: /OracleApplicationExpress/
      weight: -70
    - identifier: swift
      name: Swift
      url: /swift/
      weight: -60
    - identifier: archives
      name: Archives
      url: /archives/
      weight: -50
   
