baseURL: "https://learnerloft.com"
languageCode: en-us
title: Learner Loft
theme: PaperMod

staticDir: ["static"]

markup:
  goldmark:
    renderer:
      unsafe: true

ignoreFiles:
  - "static/devtools/*"

security:
  funcs:
    getenv:
      - ^HUGO_
      - ^NODE_

# Suppress HTML warnings
ignoreLogs:
  - 'warning-goldmark-raw-html'

params:
  defaultTheme: auto
  ShowBreadCrumbs: true
  ShowBreadCrumbsOnHome: false
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  
  homeInfoParams:
    Title: "Hello, Pals !!"
    Content: "Welcome to Learner Loft, your ultimate destination for all things tech! 
            Whether you're a seasoned developer, a budding programmer, or simply passionate about technology, 
            Learner Loft is your one-stop-shop for the latest articles and insights on HTML, SQL, Oracle APEX, and more.
            Our mission is to empower tech enthusiasts with the knowledge and resources they need to stay informed, 
            inspired, and ahead of the curve. We believe that technology has the power to transform lives and drive innovation, 
            and we're committed to sharing our passion for tech with our community."

  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowCodeCopyButtons: true
  cover:
    linkFullImages: true
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true

  # Social icons configuration moved under params
  Social:
    - name: github
      url: "https://github.com/Ashwini-Shalke/devtoolzone"

menu:
  main:
    - identifier: devtools
      name: Dev Tools
      url: /devtools/
      weight: -100
    - identifier: sql
      name: SQL
      url: /sql/
      weight: -90
    - identifier: html
      name: HTML
      url: /html/
      weight: -80
    - identifier: oracleapex
      name: Oracle APEX
      url: /OracleApplicationExpress/
      weight: -70
    - identifier: swift
      name: Swift
      url: /swift/
      weight: -60
    - identifier: archives
      name: Archives
      url: /archives/
      weight: -50
   
