baseURL: "https://learnerloft.com"
languageCode: en-us
title: Learner Loft
theme: PaperMod

params:
  homeInfoParams:
    Title: "Hello, Pals !!"
    Content: Welcome to Learner Loft. Whether you're a code ninja or a curious newbie, we've got the goodies to make your tech dreams come true.
            Get ready for a rollercoaster ride through articles, tutorials, and tools that'll make you say, "JSON, who's your daddy?" and "Word count? 
            More like word WOW!" So strap in, grab your keyboard, and let's rock this tech party!
  # socialIcons:
  #   - name: facebook
  #     url: "https://facebook.com/"
  #   - name: twitter
  #     url: "https://twitter.com/"
  #   - name: github
  #     url: "https://github.com/"

  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowCodeCopyButtons: true

  cover:
    linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true


menu:
  main:
   
    # - identifier: categories
    #   name: Categories
    #   url: /categories/
    #   weight: 10
    - identifier: SQL
      name: SQL
      url: /sql/
      weight: 10
    - identifier: HTML
      name: HTML
      url: /html/
      weight: 20
    - identifier: Oracle APEX
      name: Oracle APEX
      url: /OracleApex/
      weight: 30
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 40
   
