[build]
  command = "hugo --gc --minify"
  publish = "public"

# Build environment settings
[build.environment]
  HUGO_VERSION = "0.145.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production]
  environment = { HUGO_VERSION = "0.145.0" }