[build]
  command = "hugo --gc --minify"
  publish = "public"

[[redirects]]
  from = "/devtools/*"
  to = "/devtools/index.html"
  status = 200
  force = true

[build.environment]
  HUGO_VERSION = "0.145.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production]
  environment = { HUGO_VERSION = "0.145.0" } 