[build]
  command = """
    cd ../learnerloft-apps && npm install && npm run build && cp -r dist/* ../devtoolzone/static/devtools/ && cd ../devtoolzone && hugo --gc --minify
  """
  publish = "public"

[[redirects]]
  from = "/devtools/*"
  to = "/devtools/index.html"
  status = 200
  force = true

[build.environment]
  HUGO_VERSION = "0.145.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production]
  environment = { HUGO_VERSION = "0.145.0" }