[build]
  command = "hugo --gc --minify"
  publish = "public"

[[redirects]]
  from = "/devtools/*"
  to = "/devtools/index.html"
  status = 200

[build.environment]
  HUGO_VERSION = "0.121.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.production]
  command = "hugo --gc --minify"
  environment = { HUGO_VERSION = "0.121.1" } 